name = "workers-airtable-form"
type = "javascript"

account_id="08f641e2bafd168ed5d1c04fcbcc05af"
workers_dev = true
compatibility_date = "2023-01-18"

[vars]
AIRTABLE_BASE_ID = "appkyGa7g8ZfXKCMW"
AIRTABLE_TABLE_NAME = "Form Submissions"

